name: Check version on PR

on:
  pull_request:
    paths:
      - 'stockprice/**'
      - 'setup.py'

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update local repository
      run: git fetch origin main

    - name: Check version
      run: |
        PR_VERSION=$(git show HEAD:setup.py | grep -Eo "version=\"[0-9]+\.[0-9]+\.[0-9]+\"" | cut -d '"' -f 2)
        MAIN_VERSION=$(git show origin/main:setup.py | grep -Eo "version=\"[0-9]+\.[0-9]+\.[0-9]+\"" | cut -d '"' -f 2)
        if [ "$MAIN_VERSION" = "$PR_VERSION" ]; then
          echo "Error: PR uses the same version as the main branch"
          exit 1
        else
          echo "Versions are different"
        fi
