name: Check version on PR

on:
  pull_request:
    paths:
      - 'stockprice/**'
      - 'setup.py'

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Print setup.py in main branch
      run: |
        echo "Setup.py in main branch:"
        cat "$(git rev-parse --show-toplevel)/setup.py"

    - name: Print setup.py in pull request branch
      run: |
        echo "Setup.py in pull request branch:"
        cat setup.py

    - name: Get version from main branch
      run: |
        MAIN_VERSION=$(git show origin/main:setup.py | grep -Eo "version='[0-9]+\.[0-9]+\.[0-9]+'" | cut -d "'" -f 2)
        cat $MAIN_VERSION

    - name: Get version from pull request branch
      run: |
        PR_VERSION=$(git show HEAD:setup.py | grep -Eo "version='[0-9]+\.[0-9]+\.[0-9]+'" | cut -d "'" -f 2)
        cat $PR_VERSION

    - name: Check version
      run: |
        if [ "$MAIN_VERSION" = "$PR_VERSION" ]; then
          echo "Error: PR uses the same version as the main branch"
          exit 1
        else
          echo "Versions are different"
        fi
