---
name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Install pipenv
        shell: bash
        run: pipx install pipenv
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pipenv"
      - name: Pipenv install
        shell: bash
        run: pipenv install --dev
      - run: pipenv run format-check
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Install pipenv
        shell: bash
        run: pipx install pipenv
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pipenv"
      - name: Pipenv install
        shell: bash
        run: pipenv install --dev
      - run: pipenv run pytest
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Install pipenv
        shell: bash
        run: pipx install pipenv
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pipenv"
      - name: Pipenv install
        shell: bash
        run: pipenv install
      - name: smoke test stock.sh
        run: |
          shopt -s expand_aliases
          alias stockplot=${PWD}/stockplot.sh
          alias stock=${PWD}/stock.sh
          ./install.sh
          stock tsla,aapl
      - name: smoke test stockplot.sh
        run: |
          shopt -s expand_aliases
          alias stockplot=${PWD}/stockplot.sh
          alias stock=${PWD}/stock.sh
          ./install.sh
          stockplot tsla
          
