---
name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Install pipenv
        run: pipx install pipenv
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pipenv"
      - name: Pipenv install
        run: pipenv install --dev
      - run: pipenv run format-check
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Install pipenv
        run: pipx install pipenv
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pipenv"
      - name: Pipenv install
        run: pipenv install --dev
      - run: pipenv run pytest
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Install pipenv
        run: pipx install pipenv
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pipenv"
      - name: Pipenv install
        run: pipenv install
      - name: install stock-price-cli
        run: ./install.sh
      - name: smoke test stockprice
      # https://github.com/actions/toolkit/issues/766
        run: |
          shopt -s expand_aliases
          alias stockprice=${PWD}/stockprice.sh
          stockprice tsla,aapl
      - name: smoke test stockplot
      # https://github.com/actions/toolkit/issues/766
        run: |
          shopt -s expand_aliases
          alias stockplot=${PWD}/stockplot.sh
          stockplot tsla
